import random
from tablero import *
import time
# =========================================================
# ALGORITMO GENÉTICO
# =========================================================

def initialize_population(size, n):
    '''
    Creates an initial population of 'size' individuals.

    Args:
        size (int): Population size
        n (int): Number of queens
    Returns:
        list: A list where each element is a state 
           
    Genera una población de estados.
    '''
    return [initialize_random_state(n) for _ in range(size)]

def fitness(state):
    """
    Calculates a state's fitness
    Args:
        state(list): A list where state[i] is the row of the queen in column i
    Returns:
        float: fitness value


    Fitness inverso del costo: a menor costo, mayor fitness.
    """
    return 1 / (1 + cost(state))

def tournament_selection(population, k):
    """
    Selects the best of k randomly selected individuals
    Args:
        population(list): a list of states
    Returns:
        selected(list): best state
    Selecciona el mejor de k individuos al azar (torneo).
    """
    selected = random.sample(population, k)
    selected.sort(key=lambda s: cost(s))
    return selected[0]

def crossover(parent1, parent2):
    """
    Generates two childs by combining the parents structure

    Args:
        parent1(list): A state
        parent2(list): A state
    Returns:
        child1(list): A state generated by the two parents
        child2(list): A state generated by the two parents
    Cruce de un punto entre dos padres."""
    n = len(parent1)
    point = random.randint(1, n - 2)
    child1 = parent1[:point] + parent2[point:]
    child2 = parent2[:point] + parent1[point:]
    return child1, child2

def mutate(state, mutation_rate):
    """
    Changes a state structure randomly

    Args:
        state(list): A state
        mutation_rate(float): Probabilty of mutating the state
    Returns:
        new_state(list): A copy of the state or the mutated state
    Cambia aleatoriamente la fila de una reina con cierta probabilidad.
    """
    n = len(state)
    new_state = state.copy()
    if random.random() < mutation_rate:
        col = random.randint(0, n - 1)
        new_row = random.randint(0, n - 1)
        new_state[col] = new_row
    return new_state


'''
    ALGORITMO GENÉTICO
    Estructura general del algoritmo
    1. Inicializar población
    2. Evaluar población
    3. Seleccionar padres
    4. Cruzar padres para crear hijos
    5. Mutar hijos
    6. Reemplazar población
    7. Repetir desde 2 hasta criterio de terminación
'''
def genetic_algorithm(state, pop_size, generations, mutation_rate):
    """
    Genetic Algorithm to solve the N-Queens problem.
    Args:
        state (list): A list where state[i] is the row of the queen in column i.
        pop_size (int): Population size
        generations (int): Number of generations
        mutation_rate (float): Probability of mutation
    Returns:
        tuple: (best_state, best_cost, total_generations, total_time)
    """
    inicio=time.time()
    # Inicializar población, cada individuo es una copia del estado inicial
    population = [state.copy() for _ in range(pop_size)]

    for gen in range(generations):
        # Ordenar por costo (mejor al principio)
        population.sort(key=cost)
        best = population[0]
        best_cost = cost(best)

        #print(f"Generación {gen}: mejor costo = {best_cost}")
        #print_board_ascii(best)
        # Criterio de terminación
        if best_cost == 0:
            print("Solución encontrada:")
            print_board_ascii(best)
            fin=time.time()
            tiempo=fin-inicio
            return best,best_cost,gen,tiempo

        # Nueva generación con elitismo
        new_population = [best]  # conservar el mejor
        while len(new_population) < pop_size:
            parent1 = tournament_selection(population,3)
            parent2 = tournament_selection(population,3)
            child1, child2 = crossover(parent1, parent2)
            new_population.append(mutate(child1, mutation_rate))
            if len(new_population) < pop_size:
                new_population.append(mutate(child2, mutation_rate))

        population = new_population

    # Si no se encontró solución
    best = min(population, key=cost)
    fin=time.time()
    tiempo=fin-inicio
    steps=gen
    print(f"No se encontró solución. Mejor intento con costo {cost(best)}:")
    print_board_ascii(best)
    return best,best_cost,steps,tiempo
